In [1]:
from ene300.functions import shubert, griewank, sixhump, easom, eggholder
from ene300.optimization import PSO, FPA, GA
from ene300.plot import animate_pso, plot_surface

%matplotlib qt

import numpy as np

def custo(x):

    a = np.array([26.97, 1.865, 39.79])
    b = np.array([-0.3975, -0.03988, -0.3116])
    c = np.array([0.002176, 0.001138, 0.001457])
    
    PG = x
    F = 0
    for i in range(3):
        F += a[i] + b[i]*PG[i]+c[i]*PG[i]**2
    return F

def custo_regularizado(x, alpha=10):
    return custo(x) + alpha*(np.sum(x, axis=0)-550)**2

functions_params = {
    'shubert' :            dict( objective_function = shubert,
                                position_boundary = [[-10, 10],   [-10, 10]  ] ),
    'griewank' :           dict( objective_function = griewank,
                                position_boundary = [[-60, 60],   [-60, 60]  ] ),
    'sixhump' :            dict( objective_function = sixhump,
                                position_boundary = [[-3, 3],     [-2, 2]    ] ),
    'easom' :              dict( objective_function = easom,
                                position_boundary = [[-10, 10], [-10, 10]] ),
    'eggholder' :          dict( objective_function = eggholder,
                                position_boundary = [[-512, 512], [-512, 512]] ),
    'custo_regularizado' : dict( objective_function = custo_regularizado,
                                position_boundary = [[100, 196],  [50, 114]  , [200, 332]] ),
    }

In [2]:
ga = FPA()
global_best, best_fit, history = ga(   **functions_params['shubert'],
                                        population = 80, 
                                        itmax = 200, 
                                        max_fa = 200,
                                        direction='maximize',p=0.75)
best_fit

198.8640303529496

In [3]:
history['global_best']

[array([-5.68373009,  4.02680036]),
 array([-5.68373009,  4.02680036]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([-0.62966128, -0.89041902]),
 array([ 5.47464543, -7.2426

In [4]:
history['iteration'][-1]

199

In [5]:
history['best_fit']

[98.90651552387087,
 98.90651552387087,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 130.66608760188058,
 149.6303911466612,
 149.6303911466612,
 149.6303911466612,
 149.6303911466612,
 149.6303911466612,
 149.6303911466612,
 149.6303911466612,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529496,
 198.8640303529

In [6]:
history['objective_function'](global_best)

198.8640303529496

In [7]:
history['function_evaluations']

200

In [8]:
plot_surface(history, cmap='viridis', alpha=0.4)

In [9]:
history['cpu_time']

0.8619601490000002